### ISSUE TITLE
CORS Regex

### ISSUE THREAD

**Issue by saifulkhan** [ScottishCovidResponse/rampvis-api#23]
For example test: https://deploy-preview-119--rampvis-ui-development.netlify.app/page?id=6181746e3f35852412f6b3b4

**Comment by kachkaev** [comment]
Happy to submit a PR for that to unblock us

**Comment by saifulkhan** [comment]
It will be great :)

**Comment by kachkaev** [comment]
Done in #27

**Comment by saifulkhan** [comment]
Looks like the issue is still there. 


 Test cases:

1. infrastructure-api (Javascript): Open and see if the list of dashboards are loaded  https://deploy-preview-119--rampvis-ui-development.netlify.app/dashboard

2. data-api (Python): Open and see if the data is being served https://deploy-preview-119--rampvis-ui-development.netlify.app//stat/v1/data/?product=phe&component=newPeopleVaccinatedThirdInjectionByPublishDate&format=long



The CORS check in the Python API happens in: https://github.com/ScottishCovidResponse/rampvis-api/blob/main/data-api/app/main.py#L19 We need to review this part of the code too.

**Comment by kachkaev** [comment]
@saifulkhan what is the value of our env var? Do we have `*--rampvis-ui-development.netlify.app` in the list of origins?

I did not know about the python routes, not sure what to suggest there!

**Comment by saifulkhan** [comment]
Yes, I shared the config (it's a private repo) folder with you.  https://github.com/saifulkhan/rampvis-config/blob/main/production.json

**Comment by kachkaev** [comment]
Right. Looks like we’ll need to enable `allow_origin_regex` in python change the config to some regex 🤔

https://fastapi.tiangolo.com/tutorial/cors/

JS implementation would need to change too for parity.

**Comment by kachkaev** [comment]
Let me give it a try now

**Comment by saifulkhan** [comment]
Yes, I wonder what should be the value of allow_origin_regex, "*--rampvis-ui-development.netlify.app"?

**Comment by kachkaev** [comment]
#28

**Comment by kachkaev** [comment]
# 🤞
